#!/bin/bash

set -e
set -o pipefail

########################################################################
# Load modules
module load python/3.9.9
module load R/4.4.0

########################################################################
# Set up running directory
cd "$(dirname "${BASH_SOURCE[0]}")" 

# Read root path
rootdir=$(realpath "./../..")
echo "$rootdir"

########################################################################
# Read multiple values and assign them to variables by parsing yaml file
cellranger_parameters=$(cat ${rootdir}/project_parameters.Config.yaml | grep 'cellranger_parameters:' | awk '{print $2}')
cellranger_parameters=${cellranger_parameters//\"/}
echo "$cellranger_parameters"

multi_config_dir=$(cat ${rootdir}/project_parameters.Config.yaml | grep 'multi_config_dir:' | awk '{print $2}')
multi_config_dir=${multi_config_dir//\"/}
echo "multi_config dir: $multi_config_dir"

########################################################################
# Create directories to save output files to
summary_base_dir="./results/03_cellranger_count_summary/${cellranger_parameters}/multi_run_${cellranger_parameters}"
mkdir -p "$summary_base_dir"
echo "$summary_base_dir"

module_dir="${rootdir}/analyses/cellranger-analysis"
results_dir="${module_dir}/results"
multi_count_base="${results_dir}/02_cellranger_count/${cellranger_parameters}"
echo "$multi_count_base"

##################################################################################################
# Step 1 #########################################################################################
# We need to transform the CSV file for each sample to match the one from cellranger count
Rscript --vanilla j2-prepare-CSV.R

##################################################################################################
# Step 2 #########################################################################################
# Run to summarize results generated by CellRanger for all libraries
python "${module_dir}/util/summarize_cellranger_results.py" \
        --dir="./results/02_cellranger_count/${cellranger_parameters}" \
        --outdir="$summary_base_dir"